; OAM CONSTANTS
DEF BYTES_IN_OAM_OBJECT = 4
DEF OAM_START_ADDR = $FE00
DEF OAM_X_DISPLACEMENT = 8
DEF OAM_Y_DISPLACEMENT = 16

; TILES CONSTANTS
DEF LAST_TILE_ADDR = $7F

; ENTITIES CONSTANTS
DEF NOT_OAM_EXTRA_ATTRIBUTES = 3

def MAX_ENTITIES = 10
def ENTITY_SIZE = 5

def MAX_BLOCKS = 10
def BLOCK_SIZE = 4

def POS_X = 0
def POS_Y = 1
def N_TILES = 2
def ATTRIBUTES  = 3
def WIDTH = 4
def HEIGHT = 5
def TYPE = 6
def LIFE = 7
def DMG = 8