; OAM CONSTANTS
DEF BYTES_IN_OAM_OBJECT = 4
DEF OAM_START_ADDR = $FE00
DEF OAM_X_DISPLACEMENT = 8
DEF OAM_Y_DISPLACEMENT = 16

; TILES CONSTANTS
DEF LAST_TILE_ADDR = $7F

; ENTITIES CONSTANTS
DEF NOT_OAM_EXTRA_ATTRIBUTES = 3
